# Generated by Django 2.2.2 on 2020-01-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_backend', '0003_alltransfer_answermessage_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDealsMessageIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('id_user', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'active_deals_message_ids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'template_texts',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='TopTimetable',
        ),
    ]
